name: Build and deploy

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get repository name
        id: repository-name
        run: |
          REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          echo ::set-output name=repository::$REPOSITORY

      - name: Get Fvm config
        uses: kuhnroyal/flutter-fvm-config-action/setup@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true

      - name: Build
        run: flutter build web --base-href /${{ steps.repository-name.outputs.repository }}/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
